FROM nginx:1.13.3-alpine
RUN rm -rf /usr/share/nginx/html/*
## From 'builder' stage copy over the artifacts in dist folder to default nginx public folder
COPY dist /usr/share/nginx/html
#docker build -t  notificationconfig . --file Dockerfile.txt

#docker run -d -it -p 80:80/tcp --name notificationconfig-container notificationconfig 
#sudo vmhgfs-fuse .host:/ /mnt/hgfs/ -o allow_other -o uid=1000